# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05f70dd365dabd0fa3aea5c9d2a6f8d192ab84e43aca3bf2671cfe7339655a711919691110e3baa9929658b0bebaed2b5ebeaf46c05defd8b79ebc0838532115

test:
  secret_key_base: 584c5f78bcb508597216656fa85c5081cc4dfd38742488831f7b7fa140ace62c96941b724c7a54027f5c79e00814906f41a2f8949c1683d208549da3f64f3598

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
